// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: district.proto

package setting_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type District struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RuName string        `protobuf:"bytes,2,opt,name=ru_name,json=ruName,proto3" json:"ru_name,omitempty"`
	Name   string        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Soato  uint32        `protobuf:"varint,4,opt,name=soato,proto3" json:"soato,omitempty"`
	Code   uint32        `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`
	City   *City         `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	Region *Region       `protobuf:"bytes,7,opt,name=region,proto3" json:"region,omitempty"`
	Tax    *DistrictTax  `protobuf:"bytes,8,opt,name=tax,proto3" json:"tax,omitempty"`
	Cost   *DistrictCost `protobuf:"bytes,9,opt,name=cost,proto3" json:"cost,omitempty"`
}

func (x *District) Reset() {
	*x = District{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *District) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*District) ProtoMessage() {}

func (x *District) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use District.ProtoReflect.Descriptor instead.
func (*District) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{0}
}

func (x *District) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *District) GetRuName() string {
	if x != nil {
		return x.RuName
	}
	return ""
}

func (x *District) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *District) GetSoato() uint32 {
	if x != nil {
		return x.Soato
	}
	return 0
}

func (x *District) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *District) GetCity() *City {
	if x != nil {
		return x.City
	}
	return nil
}

func (x *District) GetRegion() *Region {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *District) GetTax() *DistrictTax {
	if x != nil {
		return x.Tax
	}
	return nil
}

func (x *District) GetCost() *DistrictCost {
	if x != nil {
		return x.Cost
	}
	return nil
}

type CreateUpdateDistrict struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RuName   string `protobuf:"bytes,2,opt,name=ru_name,json=ruName,proto3" json:"ru_name,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CityId   string `protobuf:"bytes,4,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	RegionId string `protobuf:"bytes,5,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Soato    uint32 `protobuf:"varint,6,opt,name=soato,proto3" json:"soato,omitempty"`
	Code     uint32 `protobuf:"varint,7,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *CreateUpdateDistrict) Reset() {
	*x = CreateUpdateDistrict{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUpdateDistrict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUpdateDistrict) ProtoMessage() {}

func (x *CreateUpdateDistrict) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUpdateDistrict.ProtoReflect.Descriptor instead.
func (*CreateUpdateDistrict) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUpdateDistrict) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateUpdateDistrict) GetRuName() string {
	if x != nil {
		return x.RuName
	}
	return ""
}

func (x *CreateUpdateDistrict) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUpdateDistrict) GetCityId() string {
	if x != nil {
		return x.CityId
	}
	return ""
}

func (x *CreateUpdateDistrict) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

func (x *CreateUpdateDistrict) GetSoato() uint32 {
	if x != nil {
		return x.Soato
	}
	return 0
}

func (x *CreateUpdateDistrict) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type DistrictTaxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DistrictId   string  `protobuf:"bytes,1,opt,name=district_id,json=districtId,proto3" json:"district_id,omitempty"`
	TaxPerSquare float32 `protobuf:"fixed32,2,opt,name=tax_per_square,json=taxPerSquare,proto3" json:"tax_per_square,omitempty"`
	TaxStartDate string  `protobuf:"bytes,3,opt,name=tax_start_date,json=taxStartDate,proto3" json:"tax_start_date,omitempty"`
}

func (x *DistrictTaxRequest) Reset() {
	*x = DistrictTaxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DistrictTaxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistrictTaxRequest) ProtoMessage() {}

func (x *DistrictTaxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistrictTaxRequest.ProtoReflect.Descriptor instead.
func (*DistrictTaxRequest) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{2}
}

func (x *DistrictTaxRequest) GetDistrictId() string {
	if x != nil {
		return x.DistrictId
	}
	return ""
}

func (x *DistrictTaxRequest) GetTaxPerSquare() float32 {
	if x != nil {
		return x.TaxPerSquare
	}
	return 0
}

func (x *DistrictTaxRequest) GetTaxStartDate() string {
	if x != nil {
		return x.TaxStartDate
	}
	return ""
}

type DistrictCostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DistrictId    string  `protobuf:"bytes,1,opt,name=district_id,json=districtId,proto3" json:"district_id,omitempty"`
	CostPerSquare float32 `protobuf:"fixed32,2,opt,name=cost_per_square,json=costPerSquare,proto3" json:"cost_per_square,omitempty"`
	CostStartDate string  `protobuf:"bytes,3,opt,name=cost_start_date,json=costStartDate,proto3" json:"cost_start_date,omitempty"`
}

func (x *DistrictCostRequest) Reset() {
	*x = DistrictCostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DistrictCostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistrictCostRequest) ProtoMessage() {}

func (x *DistrictCostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistrictCostRequest.ProtoReflect.Descriptor instead.
func (*DistrictCostRequest) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{3}
}

func (x *DistrictCostRequest) GetDistrictId() string {
	if x != nil {
		return x.DistrictId
	}
	return ""
}

func (x *DistrictCostRequest) GetCostPerSquare() float32 {
	if x != nil {
		return x.CostPerSquare
	}
	return 0
}

func (x *DistrictCostRequest) GetCostStartDate() string {
	if x != nil {
		return x.CostStartDate
	}
	return ""
}

type DistrictTax struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaxPerSquare float32 `protobuf:"fixed32,1,opt,name=tax_per_square,json=taxPerSquare,proto3" json:"tax_per_square,omitempty"`
	TaxStartDate string  `protobuf:"bytes,2,opt,name=tax_start_date,json=taxStartDate,proto3" json:"tax_start_date,omitempty"`
}

func (x *DistrictTax) Reset() {
	*x = DistrictTax{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DistrictTax) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistrictTax) ProtoMessage() {}

func (x *DistrictTax) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistrictTax.ProtoReflect.Descriptor instead.
func (*DistrictTax) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{4}
}

func (x *DistrictTax) GetTaxPerSquare() float32 {
	if x != nil {
		return x.TaxPerSquare
	}
	return 0
}

func (x *DistrictTax) GetTaxStartDate() string {
	if x != nil {
		return x.TaxStartDate
	}
	return ""
}

type DistrictCost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CostPerSquare float32 `protobuf:"fixed32,1,opt,name=cost_per_square,json=costPerSquare,proto3" json:"cost_per_square,omitempty"`
	CostStartDate string  `protobuf:"bytes,2,opt,name=cost_start_date,json=costStartDate,proto3" json:"cost_start_date,omitempty"`
}

func (x *DistrictCost) Reset() {
	*x = DistrictCost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DistrictCost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistrictCost) ProtoMessage() {}

func (x *DistrictCost) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistrictCost.ProtoReflect.Descriptor instead.
func (*DistrictCost) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{5}
}

func (x *DistrictCost) GetCostPerSquare() float32 {
	if x != nil {
		return x.CostPerSquare
	}
	return 0
}

func (x *DistrictCost) GetCostStartDate() string {
	if x != nil {
		return x.CostStartDate
	}
	return ""
}

type GetAllDistrictsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Soato    uint32 `protobuf:"varint,2,opt,name=soato,proto3" json:"soato,omitempty"`
	Page     uint32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit    uint32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	RegionId string `protobuf:"bytes,5,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	CityId   string `protobuf:"bytes,6,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
}

func (x *GetAllDistrictsRequest) Reset() {
	*x = GetAllDistrictsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllDistrictsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDistrictsRequest) ProtoMessage() {}

func (x *GetAllDistrictsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDistrictsRequest.ProtoReflect.Descriptor instead.
func (*GetAllDistrictsRequest) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllDistrictsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAllDistrictsRequest) GetSoato() uint32 {
	if x != nil {
		return x.Soato
	}
	return 0
}

func (x *GetAllDistrictsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllDistrictsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllDistrictsRequest) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

func (x *GetAllDistrictsRequest) GetCityId() string {
	if x != nil {
		return x.CityId
	}
	return ""
}

type GetAllDistrictsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count     uint32      `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Districts []*District `protobuf:"bytes,2,rep,name=districts,proto3" json:"districts,omitempty"`
}

func (x *GetAllDistrictsResponse) Reset() {
	*x = GetAllDistrictsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllDistrictsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDistrictsResponse) ProtoMessage() {}

func (x *GetAllDistrictsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDistrictsResponse.ProtoReflect.Descriptor instead.
func (*GetAllDistrictsResponse) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllDistrictsResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetAllDistrictsResponse) GetDistricts() []*District {
	if x != nil {
		return x.Districts
	}
	return nil
}

type GetAllByCityRegionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegionId string `protobuf:"bytes,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	CityId   string `protobuf:"bytes,2,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetAllByCityRegionRequest) Reset() {
	*x = GetAllByCityRegionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllByCityRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllByCityRegionRequest) ProtoMessage() {}

func (x *GetAllByCityRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllByCityRegionRequest.ProtoReflect.Descriptor instead.
func (*GetAllByCityRegionRequest) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllByCityRegionRequest) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

func (x *GetAllByCityRegionRequest) GetCityId() string {
	if x != nil {
		return x.CityId
	}
	return ""
}

func (x *GetAllByCityRegionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_district_proto protoreflect.FileDescriptor

var file_district_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x63, 0x69, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x94, 0x02, 0x0a, 0x08, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x75, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x75, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x6f, 0x61, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73,
	0x6f, 0x61, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x28, 0x0a, 0x06,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x52, 0x06,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x03, 0x74, 0x61, 0x78, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x54, 0x61, 0x78, 0x52, 0x03, 0x74, 0x61, 0x78, 0x12,
	0x2a, 0x0a, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63,
	0x74, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x22, 0xb3, 0x01, 0x0a, 0x14,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x75, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x75, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x6f, 0x61, 0x74, 0x6f,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x6f, 0x61, 0x74, 0x6f, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x22, 0x81, 0x01, 0x0a, 0x12, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x54, 0x61,
	0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x61, 0x78,
	0x5f, 0x70, 0x65, 0x72, 0x5f, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x0c, 0x74, 0x61, 0x78, 0x50, 0x65, 0x72, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x12,
	0x24, 0x0a, 0x0e, 0x74, 0x61, 0x78, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x61, 0x78, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x44, 0x61, 0x74, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x13, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x63, 0x74, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x49, 0x64, 0x12, 0x26,
	0x0a, 0x0f, 0x63, 0x6f, 0x73, 0x74, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x73, 0x71, 0x75, 0x61, 0x72,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0d, 0x63, 0x6f, 0x73, 0x74, 0x50, 0x65, 0x72,
	0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x63, 0x6f, 0x73, 0x74, 0x5f, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x63, 0x6f, 0x73, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x22, 0x59,
	0x0a, 0x0b, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x54, 0x61, 0x78, 0x12, 0x24, 0x0a,
	0x0e, 0x74, 0x61, 0x78, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c, 0x74, 0x61, 0x78, 0x50, 0x65, 0x72, 0x53, 0x71, 0x75,
	0x61, 0x72, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x61, 0x78, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x61, 0x78,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x22, 0x5e, 0x0a, 0x0c, 0x44, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x63, 0x74, 0x43, 0x6f, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x63, 0x6f, 0x73,
	0x74, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x0d, 0x63, 0x6f, 0x73, 0x74, 0x50, 0x65, 0x72, 0x53, 0x71, 0x75, 0x61, 0x72,
	0x65, 0x12, 0x26, 0x0a, 0x0f, 0x63, 0x6f, 0x73, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x73, 0x74,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x22, 0xa2, 0x01, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x6f, 0x61, 0x74,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x6f, 0x61, 0x74, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x64, 0x22, 0x61,
	0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x30, 0x0a, 0x09, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69,
	0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x52, 0x09, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74,
	0x73, 0x22, 0x65, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x79, 0x43, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63,
	0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x69,
	0x74, 0x79, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x1a, 0x5a, 0x18, 0x67, 0x65, 0x6e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_district_proto_rawDescOnce sync.Once
	file_district_proto_rawDescData = file_district_proto_rawDesc
)

func file_district_proto_rawDescGZIP() []byte {
	file_district_proto_rawDescOnce.Do(func() {
		file_district_proto_rawDescData = protoimpl.X.CompressGZIP(file_district_proto_rawDescData)
	})
	return file_district_proto_rawDescData
}

var file_district_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_district_proto_goTypes = []interface{}{
	(*District)(nil),                  // 0: genproto.District
	(*CreateUpdateDistrict)(nil),      // 1: genproto.CreateUpdateDistrict
	(*DistrictTaxRequest)(nil),        // 2: genproto.DistrictTaxRequest
	(*DistrictCostRequest)(nil),       // 3: genproto.DistrictCostRequest
	(*DistrictTax)(nil),               // 4: genproto.DistrictTax
	(*DistrictCost)(nil),              // 5: genproto.DistrictCost
	(*GetAllDistrictsRequest)(nil),    // 6: genproto.GetAllDistrictsRequest
	(*GetAllDistrictsResponse)(nil),   // 7: genproto.GetAllDistrictsResponse
	(*GetAllByCityRegionRequest)(nil), // 8: genproto.GetAllByCityRegionRequest
	(*City)(nil),                      // 9: genproto.City
	(*Region)(nil),                    // 10: genproto.Region
}
var file_district_proto_depIdxs = []int32{
	9,  // 0: genproto.District.city:type_name -> genproto.City
	10, // 1: genproto.District.region:type_name -> genproto.Region
	4,  // 2: genproto.District.tax:type_name -> genproto.DistrictTax
	5,  // 3: genproto.District.cost:type_name -> genproto.DistrictCost
	0,  // 4: genproto.GetAllDistrictsResponse.districts:type_name -> genproto.District
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_district_proto_init() }
func file_district_proto_init() {
	if File_district_proto != nil {
		return
	}
	file_city_proto_init()
	file_region_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_district_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*District); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUpdateDistrict); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DistrictTaxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DistrictCostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DistrictTax); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DistrictCost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllDistrictsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllDistrictsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllByCityRegionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_district_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_district_proto_goTypes,
		DependencyIndexes: file_district_proto_depIdxs,
		MessageInfos:      file_district_proto_msgTypes,
	}.Build()
	File_district_proto = out.File
	file_district_proto_rawDesc = nil
	file_district_proto_goTypes = nil
	file_district_proto_depIdxs = nil
}
