// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package setting_service

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DistrictServiceClient is the client API for DistrictService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DistrictServiceClient interface {
	Create(ctx context.Context, in *CreateUpdateDistrict, opts ...grpc.CallOption) (*CreatedResponse, error)
	Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*District, error)
	GetAll(ctx context.Context, in *GetAllDistrictsRequest, opts ...grpc.CallOption) (*GetAllDistrictsResponse, error)
	GetAllByCityRegion(ctx context.Context, in *GetAllByCityRegionRequest, opts ...grpc.CallOption) (*GetAllDistrictsResponse, error)
	Update(ctx context.Context, in *CreateUpdateDistrict, opts ...grpc.CallOption) (*empty.Empty, error)
	DistrictExists(ctx context.Context, in *SSExistsRequest, opts ...grpc.CallOption) (*SSExistsResponse, error)
	UpdateDistrictCost(ctx context.Context, in *DistrictCostRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	UpdateDistrictTax(ctx context.Context, in *DistrictTaxRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type districtServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDistrictServiceClient(cc grpc.ClientConnInterface) DistrictServiceClient {
	return &districtServiceClient{cc}
}

func (c *districtServiceClient) Create(ctx context.Context, in *CreateUpdateDistrict, opts ...grpc.CallOption) (*CreatedResponse, error) {
	out := new(CreatedResponse)
	err := c.cc.Invoke(ctx, "/genproto.DistrictService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *districtServiceClient) Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*District, error) {
	out := new(District)
	err := c.cc.Invoke(ctx, "/genproto.DistrictService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *districtServiceClient) GetAll(ctx context.Context, in *GetAllDistrictsRequest, opts ...grpc.CallOption) (*GetAllDistrictsResponse, error) {
	out := new(GetAllDistrictsResponse)
	err := c.cc.Invoke(ctx, "/genproto.DistrictService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *districtServiceClient) GetAllByCityRegion(ctx context.Context, in *GetAllByCityRegionRequest, opts ...grpc.CallOption) (*GetAllDistrictsResponse, error) {
	out := new(GetAllDistrictsResponse)
	err := c.cc.Invoke(ctx, "/genproto.DistrictService/GetAllByCityRegion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *districtServiceClient) Update(ctx context.Context, in *CreateUpdateDistrict, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/genproto.DistrictService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *districtServiceClient) DistrictExists(ctx context.Context, in *SSExistsRequest, opts ...grpc.CallOption) (*SSExistsResponse, error) {
	out := new(SSExistsResponse)
	err := c.cc.Invoke(ctx, "/genproto.DistrictService/DistrictExists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *districtServiceClient) UpdateDistrictCost(ctx context.Context, in *DistrictCostRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/genproto.DistrictService/UpdateDistrictCost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *districtServiceClient) UpdateDistrictTax(ctx context.Context, in *DistrictTaxRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/genproto.DistrictService/UpdateDistrictTax", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DistrictServiceServer is the server API for DistrictService service.
// All implementations must embed UnimplementedDistrictServiceServer
// for forward compatibility
type DistrictServiceServer interface {
	Create(context.Context, *CreateUpdateDistrict) (*CreatedResponse, error)
	Get(context.Context, *GetReq) (*District, error)
	GetAll(context.Context, *GetAllDistrictsRequest) (*GetAllDistrictsResponse, error)
	GetAllByCityRegion(context.Context, *GetAllByCityRegionRequest) (*GetAllDistrictsResponse, error)
	Update(context.Context, *CreateUpdateDistrict) (*empty.Empty, error)
	DistrictExists(context.Context, *SSExistsRequest) (*SSExistsResponse, error)
	UpdateDistrictCost(context.Context, *DistrictCostRequest) (*empty.Empty, error)
	UpdateDistrictTax(context.Context, *DistrictTaxRequest) (*empty.Empty, error)
	mustEmbedUnimplementedDistrictServiceServer()
}

// UnimplementedDistrictServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDistrictServiceServer struct {
}

func (UnimplementedDistrictServiceServer) Create(context.Context, *CreateUpdateDistrict) (*CreatedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedDistrictServiceServer) Get(context.Context, *GetReq) (*District, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedDistrictServiceServer) GetAll(context.Context, *GetAllDistrictsRequest) (*GetAllDistrictsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedDistrictServiceServer) GetAllByCityRegion(context.Context, *GetAllByCityRegionRequest) (*GetAllDistrictsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllByCityRegion not implemented")
}
func (UnimplementedDistrictServiceServer) Update(context.Context, *CreateUpdateDistrict) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedDistrictServiceServer) DistrictExists(context.Context, *SSExistsRequest) (*SSExistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DistrictExists not implemented")
}
func (UnimplementedDistrictServiceServer) UpdateDistrictCost(context.Context, *DistrictCostRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDistrictCost not implemented")
}
func (UnimplementedDistrictServiceServer) UpdateDistrictTax(context.Context, *DistrictTaxRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDistrictTax not implemented")
}
func (UnimplementedDistrictServiceServer) mustEmbedUnimplementedDistrictServiceServer() {}

// UnsafeDistrictServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DistrictServiceServer will
// result in compilation errors.
type UnsafeDistrictServiceServer interface {
	mustEmbedUnimplementedDistrictServiceServer()
}

func RegisterDistrictServiceServer(s grpc.ServiceRegistrar, srv DistrictServiceServer) {
	s.RegisterService(&DistrictService_ServiceDesc, srv)
}

func _DistrictService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUpdateDistrict)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistrictServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.DistrictService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistrictServiceServer).Create(ctx, req.(*CreateUpdateDistrict))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistrictService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistrictServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.DistrictService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistrictServiceServer).Get(ctx, req.(*GetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistrictService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllDistrictsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistrictServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.DistrictService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistrictServiceServer).GetAll(ctx, req.(*GetAllDistrictsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistrictService_GetAllByCityRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllByCityRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistrictServiceServer).GetAllByCityRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.DistrictService/GetAllByCityRegion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistrictServiceServer).GetAllByCityRegion(ctx, req.(*GetAllByCityRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistrictService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUpdateDistrict)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistrictServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.DistrictService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistrictServiceServer).Update(ctx, req.(*CreateUpdateDistrict))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistrictService_DistrictExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistrictServiceServer).DistrictExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.DistrictService/DistrictExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistrictServiceServer).DistrictExists(ctx, req.(*SSExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistrictService_UpdateDistrictCost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DistrictCostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistrictServiceServer).UpdateDistrictCost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.DistrictService/UpdateDistrictCost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistrictServiceServer).UpdateDistrictCost(ctx, req.(*DistrictCostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistrictService_UpdateDistrictTax_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DistrictTaxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistrictServiceServer).UpdateDistrictTax(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.DistrictService/UpdateDistrictTax",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistrictServiceServer).UpdateDistrictTax(ctx, req.(*DistrictTaxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DistrictService_ServiceDesc is the grpc.ServiceDesc for DistrictService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DistrictService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "genproto.DistrictService",
	HandlerType: (*DistrictServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _DistrictService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _DistrictService_Get_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _DistrictService_GetAll_Handler,
		},
		{
			MethodName: "GetAllByCityRegion",
			Handler:    _DistrictService_GetAllByCityRegion_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _DistrictService_Update_Handler,
		},
		{
			MethodName: "DistrictExists",
			Handler:    _DistrictService_DistrictExists_Handler,
		},
		{
			MethodName: "UpdateDistrictCost",
			Handler:    _DistrictService_UpdateDistrictCost_Handler,
		},
		{
			MethodName: "UpdateDistrictTax",
			Handler:    _DistrictService_UpdateDistrictTax_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "district_service.proto",
}
