// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: gis.proto

package setting_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GisProperty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NumGorny    string `protobuf:"bytes,2,opt,name=num_gorny,json=numGorny,proto3" json:"num_gorny,omitempty"`
	Firm        string `protobuf:"bytes,3,opt,name=firm,proto3" json:"firm,omitempty"`
	NameU       string `protobuf:"bytes,4,opt,name=name_u,json=nameU,proto3" json:"name_u,omitempty"`
	Raw         string `protobuf:"bytes,5,opt,name=raw,proto3" json:"raw,omitempty"`
	Region      string `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	District    string `protobuf:"bytes,7,opt,name=district,proto3" json:"district,omitempty"`
	ReceiveDate string `protobuf:"bytes,8,opt,name=receive_date,json=receiveDate,proto3" json:"receive_date,omitempty"`
	EndingDate  string `protobuf:"bytes,9,opt,name=ending_date,json=endingDate,proto3" json:"ending_date,omitempty"`
	KmlFolder   string `protobuf:"bytes,10,opt,name=kml_folder,json=kmlFolder,proto3" json:"kml_folder,omitempty"`
}

func (x *GisProperty) Reset() {
	*x = GisProperty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GisProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GisProperty) ProtoMessage() {}

func (x *GisProperty) ProtoReflect() protoreflect.Message {
	mi := &file_gis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GisProperty.ProtoReflect.Descriptor instead.
func (*GisProperty) Descriptor() ([]byte, []int) {
	return file_gis_proto_rawDescGZIP(), []int{0}
}

func (x *GisProperty) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GisProperty) GetNumGorny() string {
	if x != nil {
		return x.NumGorny
	}
	return ""
}

func (x *GisProperty) GetFirm() string {
	if x != nil {
		return x.Firm
	}
	return ""
}

func (x *GisProperty) GetNameU() string {
	if x != nil {
		return x.NameU
	}
	return ""
}

func (x *GisProperty) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

func (x *GisProperty) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GisProperty) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *GisProperty) GetReceiveDate() string {
	if x != nil {
		return x.ReceiveDate
	}
	return ""
}

func (x *GisProperty) GetEndingDate() string {
	if x != nil {
		return x.EndingDate
	}
	return ""
}

func (x *GisProperty) GetKmlFolder() string {
	if x != nil {
		return x.KmlFolder
	}
	return ""
}

type Geometry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coordinates string `protobuf:"bytes,1,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Type        string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *Geometry) Reset() {
	*x = Geometry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gis_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Geometry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Geometry) ProtoMessage() {}

func (x *Geometry) ProtoReflect() protoreflect.Message {
	mi := &file_gis_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Geometry.ProtoReflect.Descriptor instead.
func (*Geometry) Descriptor() ([]byte, []int) {
	return file_gis_proto_rawDescGZIP(), []int{1}
}

func (x *Geometry) GetCoordinates() string {
	if x != nil {
		return x.Coordinates
	}
	return ""
}

func (x *Geometry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Features struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Properties *GisProperty `protobuf:"bytes,1,opt,name=Properties,proto3" json:"Properties,omitempty"`
	Geometry   *Geometry    `protobuf:"bytes,2,opt,name=Geometry,proto3" json:"Geometry,omitempty"`
}

func (x *Features) Reset() {
	*x = Features{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gis_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Features) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Features) ProtoMessage() {}

func (x *Features) ProtoReflect() protoreflect.Message {
	mi := &file_gis_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Features.ProtoReflect.Descriptor instead.
func (*Features) Descriptor() ([]byte, []int) {
	return file_gis_proto_rawDescGZIP(), []int{2}
}

func (x *Features) GetProperties() *GisProperty {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Features) GetGeometry() *Geometry {
	if x != nil {
		return x.Geometry
	}
	return nil
}

type GisData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Features []*Features `protobuf:"bytes,1,rep,name=Features,proto3" json:"Features,omitempty"`
}

func (x *GisData) Reset() {
	*x = GisData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gis_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GisData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GisData) ProtoMessage() {}

func (x *GisData) ProtoReflect() protoreflect.Message {
	mi := &file_gis_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GisData.ProtoReflect.Descriptor instead.
func (*GisData) Descriptor() ([]byte, []int) {
	return file_gis_proto_rawDescGZIP(), []int{3}
}

func (x *GisData) GetFeatures() []*Features {
	if x != nil {
		return x.Features
	}
	return nil
}

type GetAllDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  uint64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit uint64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetAllDataRequest) Reset() {
	*x = GetAllDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gis_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDataRequest) ProtoMessage() {}

func (x *GetAllDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gis_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDataRequest.ProtoReflect.Descriptor instead.
func (*GetAllDataRequest) Descriptor() ([]byte, []int) {
	return file_gis_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllDataRequest) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllDataRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetAllDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Features []*Features `protobuf:"bytes,1,rep,name=Features,proto3" json:"Features,omitempty"`
	Count    uint64      `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetAllDataResponse) Reset() {
	*x = GetAllDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gis_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDataResponse) ProtoMessage() {}

func (x *GetAllDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gis_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDataResponse.ProtoReflect.Descriptor instead.
func (*GetAllDataResponse) Descriptor() ([]byte, []int) {
	return file_gis_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllDataResponse) GetFeatures() []*Features {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *GetAllDataResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_gis_proto protoreflect.FileDescriptor

var file_gis_proto_rawDesc = []byte{
	0x0a, 0x09, 0x67, 0x69, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67, 0x65, 0x6e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x92, 0x02, 0x0a, 0x0b, 0x47, 0x69, 0x73, 0x50, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x75, 0x6d,
	0x5f, 0x67, 0x6f, 0x72, 0x6e, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x75,
	0x6d, 0x47, 0x6f, 0x72, 0x6e, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x72, 0x6d, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x72, 0x6d, 0x12, 0x15, 0x0a, 0x06, 0x6e, 0x61,
	0x6d, 0x65, 0x5f, 0x75, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65,
	0x55, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x72, 0x61, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6b,
	0x6d, 0x6c, 0x5f, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6b, 0x6d, 0x6c, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x22, 0x40, 0x0a, 0x08, 0x47, 0x65,
	0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69,
	0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6f,
	0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x71, 0x0a, 0x08,
	0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x69, 0x73, 0x50, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x79, 0x52, 0x0a, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12,
	0x2e, 0x0a, 0x08, 0x47, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6f,
	0x6d, 0x65, 0x74, 0x72, 0x79, 0x52, 0x08, 0x47, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x22,
	0x39, 0x0a, 0x07, 0x47, 0x69, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2e, 0x0a, 0x08, 0x46, 0x65,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x52, 0x08, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x3d, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x5a, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2e, 0x0a, 0x08, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x08, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x1a, 0x5a, 0x18, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gis_proto_rawDescOnce sync.Once
	file_gis_proto_rawDescData = file_gis_proto_rawDesc
)

func file_gis_proto_rawDescGZIP() []byte {
	file_gis_proto_rawDescOnce.Do(func() {
		file_gis_proto_rawDescData = protoimpl.X.CompressGZIP(file_gis_proto_rawDescData)
	})
	return file_gis_proto_rawDescData
}

var file_gis_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gis_proto_goTypes = []interface{}{
	(*GisProperty)(nil),        // 0: genproto.GisProperty
	(*Geometry)(nil),           // 1: genproto.Geometry
	(*Features)(nil),           // 2: genproto.Features
	(*GisData)(nil),            // 3: genproto.GisData
	(*GetAllDataRequest)(nil),  // 4: genproto.GetAllDataRequest
	(*GetAllDataResponse)(nil), // 5: genproto.GetAllDataResponse
}
var file_gis_proto_depIdxs = []int32{
	0, // 0: genproto.Features.Properties:type_name -> genproto.GisProperty
	1, // 1: genproto.Features.Geometry:type_name -> genproto.Geometry
	2, // 2: genproto.GisData.Features:type_name -> genproto.Features
	2, // 3: genproto.GetAllDataResponse.Features:type_name -> genproto.Features
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gis_proto_init() }
func file_gis_proto_init() {
	if File_gis_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gis_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GisProperty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gis_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Geometry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gis_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Features); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gis_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GisData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gis_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gis_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gis_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gis_proto_goTypes,
		DependencyIndexes: file_gis_proto_depIdxs,
		MessageInfos:      file_gis_proto_msgTypes,
	}.Build()
	File_gis_proto = out.File
	file_gis_proto_rawDesc = nil
	file_gis_proto_goTypes = nil
	file_gis_proto_depIdxs = nil
}
