// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: global_setting.proto

package setting_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GlobalSetting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConstructionCost int64  `protobuf:"varint,1,opt,name=construction_cost,json=constructionCost,proto3" json:"construction_cost,omitempty"`
	LandTaxJuridical int64  `protobuf:"varint,2,opt,name=land_tax_juridical,json=landTaxJuridical,proto3" json:"land_tax_juridical,omitempty"`
	LandTaxPhysical  int64  `protobuf:"varint,3,opt,name=land_tax_physical,json=landTaxPhysical,proto3" json:"land_tax_physical,omitempty"`
	MinimumWage      int64  `protobuf:"varint,4,opt,name=minimum_wage,json=minimumWage,proto3" json:"minimum_wage,omitempty"`
	Type             string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *GlobalSetting) Reset() {
	*x = GlobalSetting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_global_setting_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalSetting) ProtoMessage() {}

func (x *GlobalSetting) ProtoReflect() protoreflect.Message {
	mi := &file_global_setting_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalSetting.ProtoReflect.Descriptor instead.
func (*GlobalSetting) Descriptor() ([]byte, []int) {
	return file_global_setting_proto_rawDescGZIP(), []int{0}
}

func (x *GlobalSetting) GetConstructionCost() int64 {
	if x != nil {
		return x.ConstructionCost
	}
	return 0
}

func (x *GlobalSetting) GetLandTaxJuridical() int64 {
	if x != nil {
		return x.LandTaxJuridical
	}
	return 0
}

func (x *GlobalSetting) GetLandTaxPhysical() int64 {
	if x != nil {
		return x.LandTaxPhysical
	}
	return 0
}

func (x *GlobalSetting) GetMinimumWage() int64 {
	if x != nil {
		return x.MinimumWage
	}
	return 0
}

func (x *GlobalSetting) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GSGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *GSGetReq) Reset() {
	*x = GSGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_global_setting_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GSGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GSGetReq) ProtoMessage() {}

func (x *GSGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_global_setting_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GSGetReq.ProtoReflect.Descriptor instead.
func (*GSGetReq) Descriptor() ([]byte, []int) {
	return file_global_setting_proto_rawDescGZIP(), []int{1}
}

func (x *GSGetReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_global_setting_proto protoreflect.FileDescriptor

var file_global_setting_proto_rawDesc = []byte{
	0x0a, 0x14, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xcd, 0x01, 0x0a, 0x0d, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x12, 0x2b, 0x0a, 0x11, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x63,
	0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x73, 0x74, 0x12,
	0x2c, 0x0a, 0x12, 0x6c, 0x61, 0x6e, 0x64, 0x5f, 0x74, 0x61, 0x78, 0x5f, 0x6a, 0x75, 0x72, 0x69,
	0x64, 0x69, 0x63, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x6c, 0x61, 0x6e,
	0x64, 0x54, 0x61, 0x78, 0x4a, 0x75, 0x72, 0x69, 0x64, 0x69, 0x63, 0x61, 0x6c, 0x12, 0x2a, 0x0a,
	0x11, 0x6c, 0x61, 0x6e, 0x64, 0x5f, 0x74, 0x61, 0x78, 0x5f, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63,
	0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x6c, 0x61, 0x6e, 0x64, 0x54, 0x61,
	0x78, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x69, 0x6e,
	0x69, 0x6d, 0x75, 0x6d, 0x5f, 0x77, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x57, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x1e, 0x0a, 0x08, 0x47, 0x53, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x42, 0x1a, 0x5a, 0x18, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_global_setting_proto_rawDescOnce sync.Once
	file_global_setting_proto_rawDescData = file_global_setting_proto_rawDesc
)

func file_global_setting_proto_rawDescGZIP() []byte {
	file_global_setting_proto_rawDescOnce.Do(func() {
		file_global_setting_proto_rawDescData = protoimpl.X.CompressGZIP(file_global_setting_proto_rawDescData)
	})
	return file_global_setting_proto_rawDescData
}

var file_global_setting_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_global_setting_proto_goTypes = []interface{}{
	(*GlobalSetting)(nil), // 0: genproto.GlobalSetting
	(*GSGetReq)(nil),      // 1: genproto.GSGetReq
}
var file_global_setting_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_global_setting_proto_init() }
func file_global_setting_proto_init() {
	if File_global_setting_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_global_setting_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalSetting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_global_setting_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GSGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_global_setting_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_global_setting_proto_goTypes,
		DependencyIndexes: file_global_setting_proto_depIdxs,
		MessageInfos:      file_global_setting_proto_msgTypes,
	}.Build()
	File_global_setting_proto = out.File
	file_global_setting_proto_rawDesc = nil
	file_global_setting_proto_goTypes = nil
	file_global_setting_proto_depIdxs = nil
}
