// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: setting_response.proto

package setting_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CTCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CTCreateResponse) Reset() {
	*x = CTCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_setting_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CTCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTCreateResponse) ProtoMessage() {}

func (x *CTCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_setting_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTCreateResponse.ProtoReflect.Descriptor instead.
func (*CTCreateResponse) Descriptor() ([]byte, []int) {
	return file_setting_response_proto_rawDescGZIP(), []int{0}
}

func (x *CTCreateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CTGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CTGetRequest) Reset() {
	*x = CTGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_setting_response_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CTGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTGetRequest) ProtoMessage() {}

func (x *CTGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_setting_response_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTGetRequest.ProtoReflect.Descriptor instead.
func (*CTGetRequest) Descriptor() ([]byte, []int) {
	return file_setting_response_proto_rawDescGZIP(), []int{1}
}

func (x *CTGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CTGetByStatusIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusId string `protobuf:"bytes,1,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
}

func (x *CTGetByStatusIdRequest) Reset() {
	*x = CTGetByStatusIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_setting_response_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CTGetByStatusIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTGetByStatusIdRequest) ProtoMessage() {}

func (x *CTGetByStatusIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_setting_response_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTGetByStatusIdRequest.ProtoReflect.Descriptor instead.
func (*CTGetByStatusIdRequest) Descriptor() ([]byte, []int) {
	return file_setting_response_proto_rawDescGZIP(), []int{2}
}

func (x *CTGetByStatusIdRequest) GetStatusId() string {
	if x != nil {
		return x.StatusId
	}
	return ""
}

type CTEmptyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CTEmptyResponse) Reset() {
	*x = CTEmptyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_setting_response_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CTEmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTEmptyResponse) ProtoMessage() {}

func (x *CTEmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_setting_response_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTEmptyResponse.ProtoReflect.Descriptor instead.
func (*CTEmptyResponse) Descriptor() ([]byte, []int) {
	return file_setting_response_proto_rawDescGZIP(), []int{3}
}

type CTDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CTDeleteRequest) Reset() {
	*x = CTDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_setting_response_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CTDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTDeleteRequest) ProtoMessage() {}

func (x *CTDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_setting_response_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTDeleteRequest.ProtoReflect.Descriptor instead.
func (*CTDeleteRequest) Descriptor() ([]byte, []int) {
	return file_setting_response_proto_rawDescGZIP(), []int{4}
}

func (x *CTDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CTExistsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CTExistsRequest) Reset() {
	*x = CTExistsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_setting_response_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CTExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTExistsRequest) ProtoMessage() {}

func (x *CTExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_setting_response_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTExistsRequest.ProtoReflect.Descriptor instead.
func (*CTExistsRequest) Descriptor() ([]byte, []int) {
	return file_setting_response_proto_rawDescGZIP(), []int{5}
}

func (x *CTExistsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CTExistsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exist bool `protobuf:"varint,1,opt,name=exist,proto3" json:"exist,omitempty"`
}

func (x *CTExistsResponse) Reset() {
	*x = CTExistsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_setting_response_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CTExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTExistsResponse) ProtoMessage() {}

func (x *CTExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_setting_response_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTExistsResponse.ProtoReflect.Descriptor instead.
func (*CTExistsResponse) Descriptor() ([]byte, []int) {
	return file_setting_response_proto_rawDescGZIP(), []int{6}
}

func (x *CTExistsResponse) GetExist() bool {
	if x != nil {
		return x.Exist
	}
	return false
}

type CTGetParentStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParentStatusId string `protobuf:"bytes,1,opt,name=parent_status_id,json=parentStatusId,proto3" json:"parent_status_id,omitempty"`
}

func (x *CTGetParentStatusRequest) Reset() {
	*x = CTGetParentStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_setting_response_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CTGetParentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTGetParentStatusRequest) ProtoMessage() {}

func (x *CTGetParentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_setting_response_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTGetParentStatusRequest.ProtoReflect.Descriptor instead.
func (*CTGetParentStatusRequest) Descriptor() ([]byte, []int) {
	return file_setting_response_proto_rawDescGZIP(), []int{7}
}

func (x *CTGetParentStatusRequest) GetParentStatusId() string {
	if x != nil {
		return x.ParentStatusId
	}
	return ""
}

var File_setting_response_proto protoreflect.FileDescriptor

var file_setting_response_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x22, 0x0a, 0x10, 0x43, 0x54, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1e, 0x0a, 0x0c, 0x43, 0x54, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x35, 0x0a, 0x16, 0x43, 0x54, 0x47, 0x65, 0x74, 0x42,
	0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x49, 0x64, 0x22, 0x11, 0x0a,
	0x0f, 0x43, 0x54, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x21, 0x0a, 0x0f, 0x43, 0x54, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x21, 0x0a, 0x0f, 0x43, 0x54, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x28, 0x0a, 0x10, 0x43, 0x54, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x78, 0x69, 0x73, 0x74,
	0x22, 0x44, 0x0a, 0x18, 0x43, 0x54, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x10,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x49, 0x64, 0x42, 0x1a, 0x5a, 0x18, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_setting_response_proto_rawDescOnce sync.Once
	file_setting_response_proto_rawDescData = file_setting_response_proto_rawDesc
)

func file_setting_response_proto_rawDescGZIP() []byte {
	file_setting_response_proto_rawDescOnce.Do(func() {
		file_setting_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_setting_response_proto_rawDescData)
	})
	return file_setting_response_proto_rawDescData
}

var file_setting_response_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_setting_response_proto_goTypes = []interface{}{
	(*CTCreateResponse)(nil),         // 0: genproto.CTCreateResponse
	(*CTGetRequest)(nil),             // 1: genproto.CTGetRequest
	(*CTGetByStatusIdRequest)(nil),   // 2: genproto.CTGetByStatusIdRequest
	(*CTEmptyResponse)(nil),          // 3: genproto.CTEmptyResponse
	(*CTDeleteRequest)(nil),          // 4: genproto.CTDeleteRequest
	(*CTExistsRequest)(nil),          // 5: genproto.CTExistsRequest
	(*CTExistsResponse)(nil),         // 6: genproto.CTExistsResponse
	(*CTGetParentStatusRequest)(nil), // 7: genproto.CTGetParentStatusRequest
}
var file_setting_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_setting_response_proto_init() }
func file_setting_response_proto_init() {
	if File_setting_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_setting_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CTCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_setting_response_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CTGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_setting_response_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CTGetByStatusIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_setting_response_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CTEmptyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_setting_response_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CTDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_setting_response_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CTExistsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_setting_response_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CTExistsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_setting_response_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CTGetParentStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_setting_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_setting_response_proto_goTypes,
		DependencyIndexes: file_setting_response_proto_depIdxs,
		MessageInfos:      file_setting_response_proto_msgTypes,
	}.Build()
	File_setting_response_proto = out.File
	file_setting_response_proto_rawDesc = nil
	file_setting_response_proto_goTypes = nil
	file_setting_response_proto_depIdxs = nil
}
